title: Educational Blog
description: A blog dedicated to sharing educational content
author: Your Name
baseurl: ""
url: "https://deardigital.ai"
markdown: kramdown

# Multilingual settings
languages: ["en", "fr", "nl"]
default_lang: "en"
exclude_from_localizations: ["assets", "CNAME"]

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin


# Global permalink structure
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Defaults for posts
defaults:
  -
    scope:
      path: "_i18n/*/posts"
      type: "posts"
    values:
      layout: "post"
