name: Discussion Bot

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

permissions:
  contents: read
  discussions: write

jobs:
  respond:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Write event payload to file
        run: |
          echo '${{ toJson(github.event) }}' | jq '.' > event_payload.json
          
      - name: Run discussion bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        run: python python/main.py --github-event="${{ github.event_name }}" --event-payload-file="event_payload.json" 