name: Issue Comment Workflow

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: self-hosted  # This specifies that the job should run on a self-hosted runner

    steps:
      - name: Check for Duplicate Issues
        id: duplicate_check
        run: |
          # Get the issue title and body
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Fetch recent open issues
          OPEN_ISSUES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&per_page=15" | \
            jq -r '.[] | select(.number != ${{ github.event.issue.number }}) | "Issue #\(.number): \(.title)\nDescription: \(.body)\n"')
          
          # Create the prompt text
          PROMPT_TEXT="You are a helpful issue analyzer for a GitHub repository. Your task is to determine if a new issue is likely a duplicate of existing open issues.

          New Issue Title: $ISSUE_TITLE
          New Issue Body: $ISSUE_BODY

          Existing Open Issues:
          $OPEN_ISSUES

          Is this a duplicate? Respond with ONLY ONE of these exact formats:
          1. If it's a duplicate: \"DUPLICATE:#X\" where X is the issue number it duplicates
          2. If it's not a duplicate: \"UNIQUE\"
          
          Don't include any other text in your response."
          
          # Create JSON payload for Ollama
          JSON_PAYLOAD="{\"model\": \"qwq:latest\", \"prompt\": $(echo "$PROMPT_TEXT" | jq -Rs .), \"stream\": false}"
          
          # Call Ollama API to analyze for duplicates
          DUPLICATE_RESULT=$(curl -s -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            http://localhost:11434/api/generate | jq -r '.response' | \
            # Filter out <think> tags and their content
            sed -E 's/<think>.*<\/think>//g' | tr -d '[:space:]')
          
          # Save the duplicate check result
          echo "result=${DUPLICATE_RESULT}" >> $GITHUB_OUTPUT
          
          # Extract duplicate issue number if applicable
          if [[ "${DUPLICATE_RESULT}" == DUPLICATE:* ]]; then
            DUPLICATE_ISSUE=$(echo "${DUPLICATE_RESULT}" | cut -d':' -f2)
            echo "duplicate_issue=${DUPLICATE_ISSUE}" >> $GITHUB_OUTPUT
            echo "is_duplicate=true" >> $GITHUB_OUTPUT
          else
            echo "is_duplicate=false" >> $GITHUB_OUTPUT
          fi

      - name: Handle Duplicate Issue
        if: steps.duplicate_check.outputs.is_duplicate == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const duplicateIssue = '${{ steps.duplicate_check.outputs.duplicate_issue }}';
            
            // Add duplicate label
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['duplicate']
            });
            
            // Comment about the duplicate
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This appears to be a duplicate of issue #${duplicateIssue}. Closing this issue as a duplicate.`
            });
            
            // Close the issue
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              state_reason: 'duplicate'
            });

      - name: Moderate Issue Content
        id: moderation
        if: steps.duplicate_check.outputs.is_duplicate != 'true'
        run: |
          # Get the issue title and body
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Create the moderation prompt text
          MODERATION_TEXT="You are a helpful issue moderator for a GitHub repository. Analyze the following issue and determine if it's relevant to a software project.

          Guidelines for classification:
          - RELEVANT: Issues that describe bugs, feature requests, or questions about the software's functionality. Even vague reports about software not working should be considered RELEVANT if they appear to be about the software.
          - IRRELEVANT: Spam, marketing, or completely unrelated content.
          - UNCLEAR: Only use this if you cannot determine if it's related to the software at all.

          Respond with ONLY ONE of these exact words: 'RELEVANT', 'IRRELEVANT', or 'UNCLEAR'. Don't include any other text in your response.
          
          Issue Title: $ISSUE_TITLE
          Issue Description: $ISSUE_BODY"
          
          # Create JSON payload for Ollama
          MODERATION_PAYLOAD="{\"model\": \"qwq:latest\", \"prompt\": $(echo "$MODERATION_TEXT" | jq -Rs .), \"stream\": false}"
          
          # Call Ollama API to analyze relevance
          MODERATION_RESULT=$(curl -s -H "Content-Type: application/json" \
            -d "$MODERATION_PAYLOAD" \
            http://localhost:11434/api/generate | jq -r '.response' | \
            # Filter out <think> tags and their content
            sed -E 's/<think>.*<\/think>//g' | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
          
          # Save the moderation result
          echo "result=${MODERATION_RESULT}" >> $GITHUB_OUTPUT
          
          # Create response prompt based on moderation result
          if [[ "$MODERATION_RESULT" == "RELEVANT" ]]; then
            RESPONSE_TEXT="You are a helpful assistant responding to a GitHub issue. This issue has been determined to be RELEVANT to the project. Generate a friendly, helpful response thanking the user for creating the issue and acknowledging their contribution. Mention that the team will review it soon. Keep it concise (2-3 sentences max) and professional. 
            
            Issue Title: $ISSUE_TITLE
            Issue Description: $ISSUE_BODY"
          elif [[ "$MODERATION_RESULT" == "IRRELEVANT" ]]; then
            RESPONSE_TEXT="You are a helpful assistant responding to a GitHub issue. This issue has been determined to be IRRELEVANT to the project. Generate a polite response explaining that the issue appears to be outside the scope of this project. Suggest that they might want to check the project documentation or create a more specific issue. Keep it concise (2-3 sentences max), professional, and non-confrontational.
            
            Issue Title: $ISSUE_TITLE
            Issue Description: $ISSUE_BODY"
          else
            RESPONSE_TEXT="You are a helpful assistant responding to a GitHub issue. The relevance of this issue is UNCLEAR. Generate a response asking for more information to help understand how this relates to the project. Be polite and helpful, suggesting what kind of details would be useful. Keep it concise (2-3 sentences max) and professional.
            
            Issue Title: $ISSUE_TITLE
            Issue Description: $ISSUE_BODY"
          fi
          
          # Create JSON payload for Ollama
          RESPONSE_PAYLOAD="{\"model\": \"qwq:latest\", \"prompt\": $(echo "$RESPONSE_TEXT" | jq -Rs .), \"stream\": false}"
          
          # Call Ollama API to generate a response
          RESPONSE=$(curl -s -H "Content-Type: application/json" \
            -d "$RESPONSE_PAYLOAD" \
            http://localhost:11434/api/generate | jq -r '.response' | \
            # Filter out <think> tags and their content
            sed -E 's/<think>.*<\/think>//g')
          
          # Save the response to an output variable, escaping newlines for GitHub Actions
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Comment on Issue
        if: steps.duplicate_check.outputs.is_duplicate != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const aiResponse = `${{ steps.moderation.outputs.response }}`;
            const moderationResult = '${{ steps.moderation.outputs.result }}';
            
            console.log(`Moderation result: ${moderationResult}`);
            
            // Fallback message in case the AI response is empty
            let message = aiResponse.trim() || 'Thanks for creating the issue. We appreciate your contribution!';
            
            // Add a label based on the moderation result
            if (moderationResult === 'RELEVANT') {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['relevant']
              });
            } else if (moderationResult === 'IRRELEVANT') {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['irrelevant']
              });
            } else {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['needs-clarification']
              });
            }
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            }); 